In [28]:
import numpy as np

In [29]:
def gaussian_elimination(A):   
    """
    Parameter
    ---------
    A : float,numpy array, 2d
        A matrix that needs to be reduced to a upper triangular form
    
    Notes
    -----
    This method is not 
    """
    nrow,ncol = int(A.shape[0]),int(A.shape[1])
    for i in range(nrow):
        for j in range(i+1,nrow):
            A[j,:] = A[j,:] - A[j,i]*A[i,:]/A[i,i]
    return A

    

In [36]:
def test_gaussian_elimination():
    B = np.array([[1,2,3],[2,3,4],[4,5,6]])
    b = gaussian_elimination(B)
    
    C = np.array([[2,3,2],[4,1,5],[6,2,3]])
    c = gaussian_elimination(C)
    return b,c

In [38]:
b,c = test_gaussian_elimination()
print(b)
print('\n')
print(c)

[[ 1  2  3]
 [ 0 -1 -2]
 [ 0  0  0]]


[[ 2  3  2]
 [ 0 -5  1]
 [ 0  0 -4]]


In [92]:
def gaussian_elimination_pivoting(A):
    """
    This function is to conduct gaussian elimination with pivoting
    
    Parameter
    ---------
    A : numpy array, 2d
        matrix to be reduced,size n*n
        
    Return
    ------
    A : Upper triangular matrix
    
    Notes
    -----
    This is more robust than the original one.
    
    """
    A = np.array(A,dtype='f')
    nrow,ncol = int(A.shape[0]),int(A.shape[1])
    
    for i in range(nrow):
        max_row = np.argmax(np.abs(A[i:,i]))# Find the largest row
        if max_row>0:
            A[[i,i+max_row],:] = A[[i+max_row,i],:]
        for j in range(i+1,nrow):
            A[j,:] = A[j,:] - A[j,i]*A[i,:]/A[i,i]
    return A


In [94]:
A = np.array([[1,1,1],[0,2,2],[0,4,5]],dtype='f')
B = np.array([[2,3,4],[0,0,2],[1,1,3]])
print(gaussian_elimination_pivoting(A))
print(gaussian_elimination_pivoting(B))



[[ 1.   1.   1. ]
 [ 0.   4.   5. ]
 [ 0.   0.  -0.5]]
[[ 2.   3.   4. ]
 [ 0.  -0.5  1. ]
 [ 0.   0.   2. ]]
