In [2]:
import numpy as np

In [33]:
#Doolittle's Factorisation
def LU_decomposition_doolittle(A):
    """
    Parameters
    ----------
    A : The matrix to be decomposed by doolittle method
    
    Returns
    -------
    L : Lower triangular matrix
    U : Upper triangular matrix
    
    """
    nrow,ncol = A.shape[0],A.shape[1]
    L = np.eye(nrow,ncol)
    U = np.zeros([ncol,nrow])

    for i in range(nrow):
        for j in range(ncol):
            s = min(i,j)
            rest_sum = np.sum([L[i,s]*U[s,j] for s in range(s+1)])
            if i<=j:
                U[i,j] = (A[i,j]-rest_sum)/L[i,s]
            else:
                L[i,j] = (A[i,j]-rest_sum)/U[s,j]
    return L,U

In [47]:
def test_doolittle_B():
    B = np.array([[2,1,-1],[4,1,0],[-2,-3,8]])
    L,U = LU_decomposition_doolittle(B)
    print(L)
    print('\n')
    print(U)
test_B()

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  2.  1.]]


[[ 2.  1. -1.]
 [ 0. -1.  2.]
 [ 0.  0.  3.]]


In [50]:
def LU_decomposition_crout(A):
    """
    Decompose a given matrix by crout method
    
    Parameters
    ----------
    A : array of float
        The matrix to be decomposed
    
    Returns
    -------
    L : Lower triangular matrix
    U : Upper triangular matrix
    
    """
    nrow,ncol = A.shape[0],A.shape[1]
    U = np.eye(nrow,ncol)
    L = np.zeros([ncol,nrow])

    for i in range(nrow):
        for j in range(ncol):
            s = min(i,j)
            rest_sum = np.sum([L[i,s]*U[s,j] for s in range(s+1)])
            if i<j:
                U[i,j] = (A[i,j]-rest_sum)/L[i,s]
            else:
                L[i,j] = (A[i,j]-rest_sum)/U[s,j]
    return L,U

In [51]:
def test_crout_A():
    A = np.array([[1,3],[4,16]])
    #B = np.array([[2,1,-1],[4,1,0],[-2,-3,8]])
    L,U = LU_decomposition_crout(A)
    print(L)
    print('\n')
    print(U)
test_crout_A()

[[1. 0.]
 [4. 4.]]


[[1. 3.]
 [0. 1.]]
